### ISSUE TITLE
meta title for site is DevFest 2017

### ISSUE THREAD

**Issue by fuentespatrick** [GDGTC/devfest#15]
From one of the marketing people at work:
"When I shared the DevFest link on LinkedIn, the meta title for the site is DevFest 2017. Can you pass that along to your fellow GDGTCers? 
https://www.linkedin.com/feed/update/urn:li:activity:6366758706176151552"

**Comment by StephenFluin** [comment]
Any idea where that's coming from? It used to be titled that (months ago) but we removed it.

**Comment by fuentespatrick** [comment]
She was making a post on LinkedIn from The Nerdery's account, I believe.
Screenshot from her here:
https://photos.app.goo.gl/FTJjKE8NHClGhw6x2

**Comment by StephenFluin** [comment]
Yep, I reproduced it myself as well, but I can't find anywhere on the site that shows this number anymore. I'm wondering if it's LinkedIn caching it. I have no idea how to flush their cache.

**Comment by lloydlentz** [comment]
I see where it is.  I had an old copy in a folder and saw it.  You can see in the src/index.html [commit](https://github.com/GDGTC/devfest/commit/b3e51d3f8dc9e9b4cf64c5b75d5b3d33ea68674d#diff-e249faefed5757034596c5096d33dab6)  that Stephen did a month ago, he removed the 2017 from the title.  Not sure how to force Linked In to update their cache.

**Comment by StephenFluin** [comment]
Closing as I don't think we can fix from our side.
